steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/qurankareem', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/qurankareem']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qurankareem'
      - '--image'
      - 'gcr.io/$PROJECT_ID/qurankareem'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_API_BASE=https://api.qurancdn.com/api/qdc,NEXT_PUBLIC_AUDIO_BASE=https://everyayah.com/data'

images:
  - 'gcr.io/$PROJECT_ID/qurankareem'

options:
  logging: CLOUD_LOGGING_ONLY